<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gf</string>
	</array>
	<key>name</key>
	<string>Grammatical Framework</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(abstract)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.gf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.gf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.module.abstract</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module_name</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(incomplete\s+)?(concrete)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.gf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.gf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.module.concrete</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module_name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>of</string>
					<key>name</key>
					<string>keyword.other.gf</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([A-z][A-z0-9_']*)\s*(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.colon.gf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=|;)</string>
			<key>name</key>
			<string>meta.function.fun-declaration.gf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_signature</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.body</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fun_judgement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flags_judgement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#oper_judgement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lin_judgement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fun|cat|def)\b</string>
			<key>name</key>
			<string>keyword.abstract</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(flags|open|with|in)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|\*\*|\+\+|\+|-&gt;|:)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>".*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(incomplete\s+)?conxxcrete (\w+) of (\w+)</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{-</string>
					<key>end</key>
					<string>-\}</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(--).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-dash</string>
				</dict>
			</array>
		</dict>
		<key>declaration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.gf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*fun)?\s*([A-z][A-z0-9_', ]*)\s*(:)</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<key>definition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-z][A-z0-9_']*)(\s+[A-z][A-z0-9_']*)*\s*(=)</string>
			<key>name</key>
			<string>definition.single-line</string>
		</dict>
		<key>flags_judgement</key>
		<dict>
			<key>match</key>
			<string>\b(flags)\s*$</string>
			<key>name</key>
			<string>support.function.gf</string>
		</dict>
		<key>fun_judgement</key>
		<dict>
			<key>match</key>
			<string>\b(fun|data|def)\s*$</string>
			<key>name</key>
			<string>support.function.gf</string>
		</dict>
		<key>lin_judgement</key>
		<dict>
			<key>match</key>
			<string>\b(lin|lincat)\b</string>
			<key>name</key>
			<string>support.function.gf</string>
		</dict>
		<key>module_name</key>
		<dict>
			<key>match</key>
			<string>[A-Z][A-z0-9._']*</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<key>oper_judgement</key>
		<dict>
			<key>match</key>
			<string>\b(oper)\s*$</string>
			<key>name</key>
			<string>support.function.gf</string>
		</dict>
		<key>type_signature</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.module.gf</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Z][A-Za-z]*\.)?([A-z][A-z0-9_']*)</string>
					<key>name</key>
					<string>meta.class-constraint.haskell</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>keyword.other.arrow.gf</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-z][A-Z0-9_']*\b</string>
					<key>name</key>
					<string>variable.other.type.gf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gf</string>
	<key>uuid</key>
	<string>7900e51b-46bc-4777-abb8-32d7e0dbb486</string>
</dict>
</plist>
